kind: ConfigMap
apiVersion: v1
metadata:
  name: codeflare-operator-config
data:
  config.yaml: |
    kuberay:
      rayDashboardOAuthEnabled: false
      ingressDomain: "kind"
      certGeneratorImage: quay.io/project-codeflare/ray:2.20.0-py39-cu118
    appwrapper:
      enabled: true
