name: Upstream to Downstream - Release Auto-Merge
on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  trigger-auto-sync:
    runs-on: ubuntu-latest
    steps:
      - name: call-sync-workflow
        run: |
          gh workflow run auto-merge-sync.yaml --repo github.com/red-hat-data-services/codeflare-operator --ref main
        env:
          GITHUB_TOKEN: ${{ secrets.CODEFLARE_MACHINE_ACCOUNT_TOKEN }}
        shell:
          bash
